apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  strategy: {}
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
